### ISSUE TITLE
preprocessing and training scripts

### ISSUE THREAD

**Issue by hermancollin** [axondeepseg/model_seg_nerve#2]
Preprocessing, training and inference scripts should be put in a `nnunet_scripts` folder. @carlosnazzarian can you confirm you have access to this repo? e.g. assign yourself to this issue

List of things to add:
- [x] script to convert data to nnunet format (see example [here](https://github.com/axondeepseg/model_seg_unmyelinated_tem/blob/main/stanford_pipeline/convert_bids_to_nnunetv2_format.py))
- [x] setup_nnunet (for env vars)
- [x] training script
- [x] inference script (probably this one: [run_inference.py](https://github.com/axondeepseg/model_seg_generalist/blob/main/nnunet_scripts/run_inference.py))

**Comment by carlosnazzarian** [comment]
@hermancollin i confirm  that i have access to this repository
